import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./_providers/Providers";
// import { UserStoreProvider } from "./_providers/userStoreProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
// import LoadingOverlay from "./_providers/LoadingOverlay";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <Providers session={session!}>
          {/* <UserStoreProvider> */}
          {/* <LoadingOverlay> */}
          {children}

          {/* </LoadingOverlay> */}
          {/* </UserStoreProvider> */}
        </Providers>
      </body>
    </html>
  );
}
